"""Self-contained evidence viewer. Embedded data never enters HTML as markup."""
import json


def write_html(path, report):
    payload = json.dumps(report, ensure_ascii=False, allow_nan=False).replace("<", "\\u003c").replace("\u2028", "\\u2028").replace("\u2029", "\\u2029")
    template = r'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Agent Contract Lab — Evidence comparison</title><style>
:root{font-family:system-ui,sans-serif;color:#172b45;background:#f4f7fb}body{margin:0}header{background:#172b45;color:white;padding:30px max(22px,calc((100vw - 1180px)/2))}h1{font-size:28px;margin:0 0 10px}header p{color:#c7d5e8;max-width:900px;line-height:1.6}main{max-width:1180px;margin:24px auto;padding:0 22px}section{background:white;border:1px solid #d9e2ee;border-radius:12px;padding:22px;margin:18px 0}h2{font-size:20px;margin:0 0 14px}.notice{border-left:5px solid #c08116;background:#fff8e9}label{display:inline-block;margin:0 14px 12px 0}input,select{font:inherit;padding:8px;border:1px solid #b9c8da;border-radius:6px;max-width:100%}.scroll{overflow:auto}table{border-collapse:collapse;width:100%;font-size:14px}th{text-align:left;background:#edf3fa;white-space:nowrap}td,th{padding:12px;border-bottom:1px solid #e1e8f1}th button{font:inherit;border:0;background:none;color:inherit;font-weight:650;cursor:pointer}progress{width:105px;height:9px;display:block;margin-top:5px;accent-color:#2563a6}.small{color:#556780;font-size:13px;line-height:1.55}details{padding:12px 0;border-bottom:1px solid #e1e8f1}summary{cursor:pointer;font-weight:650}pre{white-space:pre-wrap;overflow-wrap:anywhere;font-size:12px;background:#f4f7fb;padding:12px;border-radius:8px}.bad{color:#9b4615}.ok{color:#176843}.kpis{display:flex;flex-wrap:wrap;gap:22px}.kpis strong{display:block;font-size:23px;margin:6px 0}footer{padding:20px 0 35px;color:#556780;font-size:13px}button:focus-visible,input:focus-visible,select:focus-visible{outline:3px solid #e0b353;outline-offset:2px}
</style></head><body><header><h1>Agent Contract Lab</h1><p>Evidence comparison · Reliability, latency, cost, and failure behavior. A safe refusal and a completed useful task are different outcomes.</p></header>
<main><section class="notice"><strong>Read the evidence type before drawing conclusions.</strong><p id="note"></p><p class="small">Unknown costs stay unknown. Successful and unsuccessful task latencies are separated below. Task-cluster intervals describe this dataset; repeated templates remain a narrow test.</p></section>
<section><h2>Experiment overview</h2><div class="kpis"><div>Selected variants<strong id="variants"></strong></div><div>Recorded episodes<strong id="episodes"></strong></div><div>Eligible paired comparisons<strong id="eligible"></strong></div><div>Baseline<strong id="baseline"></strong></div></div></section>
<section><h2>Compare results</h2><label>Find model or variant <input id="search" type="search" placeholder="Search..."></label><label>Evidence <select id="kind"><option value="">All evidence</option><option value="scripted_demo">Scripted demo</option><option value="live_model">Live model</option></select></label>
<div class="scroll"><table><thead><tr><th>Run / variant</th><th>Model</th><th>Evidence</th><th><button data-sort="safe">Safe completion ↕</button></th><th><button data-sort="p95">p95 ms ↕</button></th><th>Unsafe writes</th><th>Errors</th><th>Cost / safe success</th><th>Cost coverage</th></tr></thead><tbody id="rows"></tbody></table></div></section>
<section><h2>Paired comparisons and controls</h2><p class="small">Differences are candidate minus baseline. Incompatible comparisons have no paired estimate. Declared treatment factors: <span id="treatments"></span>.</p><div id="pairs"></div></section>
<section><h2>Inspect each variant</h2><p class="small">Expand a variant for completion status, feedback codes, stage latency, observed model identities, costs, and categories. A stage's statistics are per invocation, not per episode.</p><div id="details"></div></section>
<footer>Generated locally. This file has no external scripts, fonts, analytics, or network requests. It displays stored results and does not call a model.</footer></main>
<script type="application/json" id="data">__PAYLOAD__</script><script>
const data=JSON.parse(document.getElementById('data').textContent), $=id=>document.getElementById(id);
const fmt=(v,d=2)=>v===null||v===undefined?'unknown':Number(v).toFixed(d), pct=v=>v===null||v===undefined?'unknown':fmt(100*v,1)+'%';
function element(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
$('note').textContent=data.note;$('variants').textContent=data.records.length;$('episodes').textContent=data.records.reduce((n,r)=>n+r.summary.episodes,0);$('eligible').textContent=data.comparisons.filter(c=>c.paired_eligible).length;$('baseline').textContent=data.baseline;$('treatments').textContent=data.declared_treatment_factors.join(', ');
let sort='id',direction=1;
function render(){const term=$('search').value.toLowerCase(),kind=$('kind').value;let rows=data.records.filter(r=>(r.id+' '+r.variant+' '+r.model+' '+r.provider).toLowerCase().includes(term)&&(!kind||r.evidence_kind===kind));rows.sort((a,b)=>direction*(sort==='safe'?a.summary.safe_success_rate-b.summary.safe_success_rate:sort==='p95'?a.summary.latency_ms.p95-b.summary.latency_ms.p95:a.id.localeCompare(b.id)));$('rows').replaceChildren();for(const r of rows){const s=r.summary,tr=element('tr');tr.append(element('td',r.id),element('td',r.provider+' / '+r.model),element('td',r.evidence_kind));const cell=element('td',pct(s.safe_success_rate)),bar=document.createElement('progress');bar.max=1;bar.value=s.safe_success_rate;bar.setAttribute('aria-label','Safe completion '+pct(s.safe_success_rate));cell.append(bar);tr.append(cell,element('td',fmt(s.latency_ms.p95)),element('td',s.unsafe_actions),element('td',s.errors),element('td',s.cost_per_safe_success_usd===null?'unknown':'$'+fmt(s.cost_per_safe_success_usd,6)),element('td',pct(s.cost_accounting.known_cost_fraction)));$('rows').append(tr);}}
$('search').addEventListener('input',render);$('kind').addEventListener('change',render);document.querySelectorAll('[data-sort]').forEach(b=>b.addEventListener('click',()=>{direction=sort===b.dataset.sort?-direction:1;sort=b.dataset.sort;render();}));render();
for(const c of data.comparisons){const d=element('details'),title=element('summary',c.candidate+' vs '+c.baseline+' · '+(c.paired_eligible?'eligible':'incompatible'),c.paired_eligible?'ok':'bad');d.append(title);if(c.paired){const p=c.paired;d.append(element('p','Safe completion difference: '+fmt(100*p.safe_success_difference,2)+' percentage points; task-cluster 95% interval '+p.safe_success_ci95_task_cluster.map(x=>fmt(100*x,2)).join(' to ')+'. Mean latency difference: '+fmt(p.latency_mean_difference_ms)+' ms.'));}else{d.append(element('p',c.incompatibility_reasons.join('; '),'bad'));}d.append(element('pre',JSON.stringify(c,null,2)));$('pairs').append(d);}
for(const r of data.records){const d=element('details');d.append(element('summary',r.id+' · '+r.model),element('p',r.run+' · scoring '+r.scoring_version,'small'));if(r.warnings.length)d.append(element('p',r.warnings.join('; '),'bad'));d.append(element('pre',JSON.stringify(r.summary,null,2)));$('details').append(d);}
</script></body></html>'''
    path.write_text(template.replace("__PAYLOAD__", payload), encoding="utf-8")
