cmake_minimum_required(VERSION 3.24)
project(jh_real_components LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 23)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/bin")
set(BLAZE_INSTALL OFF CACHE BOOL "" FORCE)
set(BLAZE_TESTS OFF CACHE BOOL "" FORCE)
set(BLAZE_BENCHMARK OFF CACHE BOOL "" FORCE)
add_subdirectory(${BLAZE_SOURCE} blaze)
add_executable(jh_blaze_worker worker.cc)
target_link_libraries(jh_blaze_worker PRIVATE sourcemeta::blaze::compiler sourcemeta::blaze::evaluator sourcemeta::blaze::alterschema sourcemeta::core::json sourcemeta::core::jsonschema)
target_compile_features(jh_blaze_worker PRIVATE cxx_std_23)
